version: '3'
services:
  washmen-url-converter:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/washmen
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
